name: build
on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: build
        run:
          $ver = git describe --always
          cho VERSION=${ver} >> $env:GITHUB_ENV
          mkdir build
          cd build
          cmake .. -DCLANG_SUFFIX=
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: squiroll-${{ env.VERSION }}
          path: |
            build/Netcode.dll
            build/th155r.exe
